WITH TOTALSALES AS (
    SELECT ORD.ORDER_ID,
    ORD.CUSTOMER_ID,
    CST.CUST_FIRST_NAME || ' ' || CST.CUST_LAST_NAME AS CUSTOMER_NAME,
    ORD.ORDER_DATE,
    TO_CHAR(ORD.ORDER_DATE, 'yyyy-MM') AS YEAR_MONTH,
    ODI.UNIT_PRICE,
    ODI.QUANTITY,
    ODI.UNIT_PRICE* ODI.QUANTITY AS TOTAL_SALES
    FROM OE.ORDERS ORD
    INNER JOIN OE.ORDER_ITEMS ODI ON
    ORD.ORDER_ID=ODI.ORDER_ID
    INNER JOIN OE.CUSTOMERS CST ON
    CST.CUSTOMER_ID = ORD.CUSTOMER_ID),

    GROUP_SALES AS(
    SELECT CUSTOMER_NAME, 
    YEAR_MONTH, 
    SUM(TOTAL_SALES) AS TOTAL_SALES
    FROM TOTALSALES
    GROUP BY CUSTOMER_NAME, YEAR_MONTH),

    RANK_SALES AS (
    SELECT CUSTOMER_NAME, 
    YEAR_MONTH,
    TOTAL_SALES, 
    RANK() OVER (PARTITION BY YEAR_MONTH ORDER BY TOTAL_SALES DESC) AS RANK_OF_MONTH,
    LAG (TOTAL_SALES) OVER (PARTITION BY CUSTOMER_NAME ORDER BY YEAR_MONTH) AS PREVIOUS_MONTHLY_SALES
    FROM GROUP_SALES
    )

SELECT CUSTOMER_NAME, 
YEAR_MONTH, 
TOTAL_SALES, 
RANK_OF_MONTH, 
PREVIOUS_MONTHLY_SALES,
TOTAL_SALES-PREVIOUS_MONTHLY_SALES AS COMPARISON
FROM RANK_SALES
ORDER BY YEAR_MONTH, RANK_OF_MONTH;